
.PHONY: all
all: repos/remote-repo repos/tagged-repo repos/commit-in-repo

repos/remote-repo:
	./create-remote-repo.sh

repos/tagged-repo:
	./create-tagged-repo.sh

repos/commit-in-repo:
	./create-commit-in-repo.sh