
.PHONY: all
all: repos/v0.1.0-dev-repo repos/v0.2.0-repo repos/v0.3.0-dev-repo

repos/v0.1.0-dev-repo:
	./create-v0.1.0-dev-repo.sh

repos/v0.2.0-repo:
	./create-v0.2.0-repo.sh

repos/v0.3.0-dev-repo:
	./create-v0.3.0-dev-repo.sh

clean:
	rm -rf repos/v0.1.0-dev-repo repos/v0.2.0-repo repos/v0.3.0-dev-repo
