name: Dependabot Automation
on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  run:
    uses: anchore/workflows/.github/workflows/dependabot-automation.yaml@auto-merge
