name: "Manage Awaiting Response Label"

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  run:
    uses: anchore/workflows/.github/workflows/remove-awaiting-response-label.yaml@4f25313f96311410cad4173f74617654a3e46d48 # v0.3.0
    secrets:
      token: ${{ secrets.OSS_PROJECT_GH_TOKEN }}
